SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA2B2FF4}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{65ED5B8F2661BB9D}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6602A2A8EB18AAD9}" : "{96C11ECF043047FF}Configs/Bushwar_Parachute_List.conf" {
  }
 }
}