SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Bushwar Parachutes"
 m_aEntities {
  SCR_EntityCatalogEntry "{6602A2A891A181F2}" {
   m_sEntityPrefab "{02546D7D1C1469CF}Prefabs/Items/Equipment/Backpacks/ParachuteBag_T10_01.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{5C62F7D85F242A15}" {
     m_eItemType BACKPACK
     m_iSupplyCost 15
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{5CA0A9E76FDFAF3C}" {
       m_vItemRotation 30 0 -90
      }
     }
    }
   }
  }
 }
}