SCR_InventoryConfig {
 m_aLoadoutAreas {
  SCR_LoadoutArea "{6899673510A75539}" {
   m_sName "Parachute"
   m_LoadoutArea Pronto_Parachute "{689967350DC31F09}" {
   }
   m_iRow 15
   m_sIcon "{59DBCC12F964F72F}UI/Textures/InventoryIcons/InventorySlot_Parachute.edds"
  }
 }
}